### ISSUE TITLE
setters for repeatables

### ISSUE THREAD

**Issue by glenfordwilliams** [dart-lang/protobuf#102] opened 2018-05-19 12:55 UTC
having a issue where all message fields which are repeatable only have getters and no setters is there a way around this?

i found where the code generation is being done but im not certain how it goes about creating getters and setters for repeatables

**Comment by Kleak** [comment] 2018-08-02 16:40
I have also the problem :/

**Comment by rakudrama** [comment] 2018-08-02 17:49
As a work-around, try:
```dart
message.repeatedField..clear()..addAll(values);
```

**Comment by Kleak** [comment] 2018-08-02 17:53
@rakudrama there is no repeatedField field in the generated class

**Comment by kevmoo** [comment] 2018-08-02 23:28
CC @mit-mit @sortie

**Comment by sortie** [comment] 2018-08-13 08:17
CC @athomas

**Comment by sigurdm** [comment] 2019-02-26 09:39
This is a duplicate of https://github.com/grpc/grpc-dart/issues/107.

The current line is: sse the getter to get the list, and operate on that.

**Closed by sigurdm** 2019-02-26 09:39 UTC
