### ISSUE TITLE
(protoc-gen-dart) Please ask the owner of this code generator to support proto3 optional

### ISSUE THREAD

**Issue by brickpop** [dart-lang/protobuf#434] opened 2020-11-10 12:50 UTC
I'm encountering two problems while trying to compile protoc3 optional fields in Dart. As a summary:
- The readme shows `optional` fields as being supported
- Using `protoc-gen-dart@19.1.0` will fail to compile them

---

1) Using the example in the Readme won't compile:
```protobuf
message M1 {
  optional string a;
}
```

- Missing `syntax="proto3";`
- Missing `=1` on the field
- Missing `--experimental_allow_proto3_optional` protoc flag

2) Trying the updated example with `protoc  --experimental_allow_proto3_optional --dart_out=. test.proto` will still fail:
```protobuf
syntax = "proto3";

message M1 {
  optional string a = 1;
}
```

Results in:
```
test.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-dart hasn't been updated to support optional fields in proto3.
Please ask the owner of this code generator to support proto3 optional.--dart_out: 
```

Environment:
- Dart 2.10.2
- protoc-gen-dart 19.1.0
- MacOS 10.15.7

---
I saw https://github.com/dart-lang/protobuf/issues/396 as a duplicate, but without a helpful title and details, it may remain unnoticed for a while.

**Comment by mraleph** [comment] 2020-11-12 08:32
Duplicate of #396

**Closed by mraleph** 2020-11-12 08:32 UTC
